

const StatusResponse = {
    configFingerMath: {
        UPDATE_CONFIG_FINGERMATH: "Cập nhật cấu hình thành công",
    },
    center: {
        CREATE_CENTER: "Tạo admin thành công",
        UPDATE_CENTER: "Cập nhật trung tâm - trường học thành công",
        DELETE_CENTER: "Xóa trung tâm - trường học thành công",
        GET_CENTER: "Lấy trung tâm - trường học thành công"
    },
    configMath: {
        UPDATE_CONFIG_MATH: "Cập nhật cấu hình thành công",
    },
    user: {
        CREATE_USER: "Tạo tài khoản thành công",
        CREATE_CENTER: "Tạo tài khoản trung tâm thành công",
        UPDATE_USER: "Cập nhật người dùng thành công",
        ADD_STUDENT_CLASS: "Thêm học sinh vào lớp thành công",
        DELETE_USER: "Xóa người dùng thành công",
        GET_USER: "Lấy người dùng thành công",

        GET_USER_LIST_SUCCESS: "Lấy danh sách người dùng thành công",
        GET_USER_SUCCESS: "Lấy thông tin người dùng thành công",
        USER_NOT_FOUND: "Không tìm thấy người dùng",
        CHANGE_SHOWING_COLUMN_SUCCESS: "Thay đổi hiển thị trường danh bạ thành công",
        UPDATE_INFO_USER_SUCCESS: "Cập nhật thông tin người dùng thành công",
        NO_CHANGE_OR_USER_NOT_FOUND: "Không có sự thay đổi hoặc người dùng không tìm thấy",
        UPDATE_OLD_USER: "Cập nhật người dùng cũ thành công",
        CHECK_EXISTS_EMAIL_SUCCESS: "Kiểm tra email đã tồn tại thành công",
    },
    class: {
        CREATE_CLASS: "Tạo lớp thành công",
        UPDATE_CLASS: "Cập lớp thành công",
        DELETE_CLASS: "Xóa lớp thành công",
        GET_CLASS: "Lấy lớp thành công"
    },
    admin: {
        CREATE_ADMIN: "Tạo admin thành công",
        UPDATE_ADMIN: "Cập admin thành công",
        DELETE_ADMIN: "Xóa admin thành công",
        GET_ADMIN: "Lấy admin thành công"
    },
    position: {
        CREATE_POSITION: "Tạo vị trí thành công",
        UPDATE_POSITION: "Cập vị trí thành công",
        DELETE_POSITION: "Xóa vị trí thành công",
        GET_POSITION: "Lấy vị trí thành công"
    },
    //Monitor
    monitor: {
        NOT_FOUND_NAME_GROUP_EXT: "Không tìm thấy tên group !!!",
        NOT_FOUND_NAME_GROUP_EXT_OLD: "Không tìm thấy tên group cũ !!!",
        NOT_FOUND_EXTS: "Không tìm thấy các máy nhánh !!!",
        NOT_FOUND_EXTENSION: "Không tìm thấy máy nhánh !!!",
        NOT_FOUND_EXTENSION_SPY: "Không tìm thấy máy nhánh nghe lén !!!",
        NOT_FOUND_COLOR_GROUP_EXT: "Không tìm thấy màu của group !!!",
        UPDATE_GROUP_ID_FAILED: "Cập nhật group id lỗi !!!",
        CREATE_GROUP_EXT_FAILED: "Thêm nhóm máy nhánh thất bại",
        NOT_FOUND_INFO_CURRENT_USER: "Không tìm thấy thông tin của chính chủ !!!",
        NAME_GROUP_IS_EXIST: "Tên nhóm đã tồn tại !!!",
        ACCOUNT_NOT_PERMISSION_MONITOR: "Tài khoản không có quyền truy cập trang giám sát !!!",
        NOT_FOUND_GROUP_OLD: "Không tìm thấy group máy nhánh cũ",
        DELETE_GROUP_OLD_FAILED: "Xóa group máy nhánh cũ thất bại !!!",
        NOT_FOUND_INFO_CHANNEL: "Không tìm thấy thông tin channels !!!",
        HANGUP_FAILED: "Ngắt máy thất bại !!!",
        LISTEN_SPY_FAILED_NO_SIP: "Nghe lén thất bại, không tìm thấy máy nhánh !!!",
        LISTEN_SPY_FAILED_NO_SIP_SPY: "Nghe lén thất bại, không tìm thấy máy nhánh nghe lén !!!",
        LISTEN_SPY_FAILED_NO_PHONE: "Nghe lén thất bại, không tìm thấy SĐT !!!",
        LISTEN_SPY_FAILED: "Nghe lén thất bại",
        PICKUP_CALL_FAILED_NO_PARAM: "Rước máy thất bại, không tìm thấy tham số !!!",
        PICKUP_CALL_FAILED_NO_SIP_OUT: "Rước máy thất bại, không tìm thấy máy nhánh cần rước !!!",
        PICKUP_CALL_FAILED: "Rước máy thất bại!!!",
        TRANSFER_CALL_FAILED_NO_SIP: "Chuyển tiếp cuộc gọi thất bại, không tìm thấy máy nhánh !!!",
        TRANSFER_CALL_FAILED_NO_CHANNEL: "Chuyển tiếp cuộc gọi thất bại, không tìm thấy kênh gọi !!!",
        TRANSFER_CALL_FAILED: "Chuyển tiếp cuộc gọi thất bại!!!",
    },
    dial: {
        WEB_CALLING_IS_OFF: "Chưa bật tính năng gọi trên web !!!",
        NOT_ASSIGNED_SIP_CLIENT_DEFAULTS: "Chưa gán máy nhánh cho người dùng !!!",
        NOT_FOUND_PASSWORD_SIP: "Không tìm thấy mật khẩu cho máy nhánh !!!",
        EXTENSION_OR_PHONE_NOT_FOUND: "Không tìm thấy máy nhánh hoặc sđt !!!",
        NOT_FOUND_LINKED_ID: "Không tìm thấy mã cuộc gọi !!!",
        NOTE_CONTENT_NOT_FOUND: "Không tìm thấy nội dung ghi chú !!!",
    },
    auth: {
        LOGIN_SUCCESS: "Đăng nhập thành công",
        CHECK_EMAIL_TO_RESET_PASSWORD: "Vui lòng kiểm tra email để nhận đường link đặt lại mật khẩu !",
        RESET_PASSWORD_SUCCESS: "Đặt lại mật khẩu thành công",
        EMAIL_NOT_FOUND: "Email không tồn tại",
        EMAIL_OR_PASSWORD_INCORRECT: "Tài khoản đăng nhập không đúng",
        ACCOUNT_INACTIVE: "Tải khoản chưa được kích hoạt",
        LOGOUT_SUCCESS: "Đăng xuất thành công",
        UPDATE_KEY_TOKEN_SUCCESS: "Cập nhật key tokens thành công",
        CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
        CONFIRM_PASSWORD_NOT_MATCH: "Xác nhận lại mật khẩu không đúng",
        NOT_FOUND_PASSWORD_OLD: "Không tìm thấy mật khẩu cũ",
        PASSWORD_OLD_NOT_MATCH: "Mật khẩu cũ không chính xác",
        NOT_FOUND_PASSWORD_NEW: "Không tìm thấy mật khẩu mới",
        CHANGE_PASSWORD_FAILED: "Đổi mật khẩu thất bại",
        SEND_EMAIL_CHANGE_EMAIL_SUCCESS: "Gửi thay đổi email thành công",
        CHANGE_EMAIL_SUCCESS: "Thay đổi email đăng nhập thành công",
        NOT_FOUND_EMAIL_NEW: "Không tìm thấy email mới",
        CHANGE_EMAIL_FAILED: "Thay đổi email thất bại",
    },
    extension: {
        GET_LIST_EXTENSION_SUCCESS: "Lấy danh sách mấy nhánh thành công",
        GET_PASSWORD_SUCCESS: "Lấy mật khẩu thành công",
        GENERATE_QRCODE_SUCCESS: "Lấy QRCode thành công",
        CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
    },
    common: {
        NOT_FOUND_STORE: "Người dùng chưa đăng ký",
        ACCOUNT_INACTIVE: "Tài khoản của bạn đã hủy kích hoạt",
        SOMETHING_WENT_WRONG: "Something went wrong !!!",
        USER_DOES_NOT_HAVE_PERMISSION: "Bạn không có quyền truy cập",
        TOKEN_NOT_VALID: "Phiên đăng nhập đã kết thúc",
        ROLE_IS_CHANGE: "Quyền của bạn đã bị thay đổi hệ thống sẽ tự động tải lại trang sau 2s",
        NO_DATA_DOWNLOAD: "Không tìm thấy dữ liệu tải xuống",
        INSERT_DATA_SUCCESS: "Thêm dữ liệu thành công"
    },
    contact: {
        GET_LIST_CONTACT_SUCCESS: "Lấy danh sách khách hàng thành công",
        GET_CONTACTS_UPLOAD_HISTORY_SUCCESS: "Lấy lịch sử tải lên danh bạ thành công",
        DELETE_CONTACT: "Xóa khách hàng thành công",
        HAS_ONLY_ONE_SYSTEM_MANAGER: "Kiểm tra quản lý danh bạ thành công",
        UPDATE_CONTACT_SUCCESS: "Cập nhật khách hàng thành công",
        FILE_NOT_DATA: "Tệp không có dữ liệu",
        PLEASE_ENTER_COMPLETE_DATA: "Vui lòng nhập đầy đủ dữ liệu",
        UPLOAD_LIMIT_EXCEEDED: "Vui lòng chỉ tải lên tệp có tối đa 500.000 dữ liệu",
        THE_GROUP_HAS_NO_EMPLOYEES: "Nhóm không có nhân viên",
        GET_NEXT_CONTACTS_SUCCESS: "Lấy dữ liệu khách hàng tiếp theo thành công",
        THE_GROUP_HAS_NO_EMPLOYEES: "Nhóm không có nhân viên",
        GET_NEXT_CONTACTS_SUCCESS: "Lấy dữ liệu khách hàng tiếp theo thành công",
        GET_NEXT_CONTACTS_UNSUCCESS: "Không tìm thấy dữ liệu khách hàng tiếp theo",
        NOT_FOUND_EVENTS: "Không tìm thấy bất kỳ sự kiện gọi lại nào",
        NOT_FOUND_CONTACT: "Không tìm thấy dữ liệu khách hàng",
        NOT_FOUND_EVENT_DATA: "Không tìm thấy dữ liệu sự kiện gọi lại",
        NOT_FOUND_TITLE_EVENT: "Không tìm thấy tiêu đề sự kiện",
        NOT_FOUND_DESCRIPTION_EVENT: "Không tìm thấy mô tả sự kiện",
        NOT_FOUND_START_EVENT: "Không tìm thấy thời gian bắt đầu sự kiện",
        NOT_FOUND_END_EVENT: "Không tìm thấy thời gian kết thúc sự kiện",
        INSERT_EVENT_SUCCESS: "Thêm sự kiện gọi lại thành công",
        GET_EVENT_SUCCESS: "Lấy dữ liệu sự kiện gọi lại thành công",
        DELETE_EVENT_SUCCESS: "Xóa sự kiện gọi lại thành công",
        UPDATE_EVENT_SUCCESS: "Cập nhật sự kiện gọi lại thành công",
        NO_CHANGE_OR_EVENT_NOT_FOUND: "Không có sự thay đổi hoặc sự kiện gọi lại không tìm thấy",
        DELETE_EVENT_UNSUCCESS: "Xóa sự kiện gọi lại thất bại",
        GET_NAME_SUCCESS: "Lấy tên liên hệ thành công",
        NO_SIP_CLIENT_DEFAULTS: "Tài khoản chưa thêm máy nhánh",
        UNCONNECT_TO_PBX: "Kết nối tổng đài thất bại",
        DEVICE_NOT_CONNECTED: "Thiết bị chưa kết nối",
    },
    notification: {
        CREATE_NOTIFICATION_SUCCESS: "Tạo thông báo thành công",
        UPDATE_NOTIFICATION_SUCCESS: "Cập nhật thông báo thành công",
        GET_NOTIFICATION_SUCCESS: "Lấy thông báo thành công",
    },
    config: {
        GET_LIST_CONTACT_FIELD_SUCCESS: "Lấy danh sách trường danh bạ thành công",
        DELETE_CONTACT_FIELD_SUCCESS: "Xóa trường danh bạ thành công",
        CREATE_CONTACT_FIELD_SUCCESS: "Tạo trường danh bạ thành công",
        UPDATE_CONTACT_FIELD_SUCCESS: "Cập nhật trường danh bạ thành công",
        DELETE_OPTION_CONTACT_FIELD_SUCCESS: "Xóa lựa chọn trường danh bạ thành công",
        NOT_FOUND_CONTACT_FIELD: "Không tìm thấy trường danh bạ",
        CONTACT_FIELD_IS_SYSTEM_FIELD: "Trường danh bạ là trường hệ thống không thể cập nhật hoặc xóa",
        CONTACT_FIELD_IS_ALREADY_EXIST: "Trường danh bạ đã tồn tại",
        DOWNLOAD_SAMPLE_FILE_SUCCESS: "Tải xuống tệp mẫu thành công",
        NO_DATA_AVAILAIBLE: "Không có dữ liệu phù hợp",
    },
    upload: {
        UPLOAD_FILE_SUCCESS: "Tải file lên thành công",
    },
    report: {
        GET_REPORT_CALL_SUCCESS: "Lấy báo cáo lịch sử cuộc gọi thành công",
        GET_REPORT_DIAL_SUCCESS: "Lấy báo cáo chiến dịch thành công",
        DOWNLOAD_REPORT_CALL: "Tải xuống báo cáo lịch sử cuộc gọi thành công",
        DOWNLOAD_REPORT_DIAL: "Tải xuống báo cáo quay số thành công",
    },
    rbac: {
        CREATE_RESOURCE_SUCCESS: "Tạo nguồn thành công",
        CREATE_ROLE_SUCCESS: "Tạo quyền thành công",
        GET_MODULE_SUCCESS: "Lấy module thành công",
        CREATE_ROLE_SUCCESS: "Tạo quyền thành công",
        GET_RESOURCE_SUCCESS: "Lấy danh sách nguồn thành công",
        ROLE_ALREADY_EXIST: "Quyền đã tồn tại",
        GET_LIST_ROLE_SUCCESS: "Lấy danh sách quyền thành công",
        CREATE_ROLE_GROUP_SUCCESS: "Tạo nhóm quyền thành công",
        UPDATE_ROLE_GROUP_SUCCESS: "Cập nhật nhóm quyền thành công",
        DELETE_ROLE_GROUP_SUCCESS: "Xóa nhóm quyền thành công",
        GET_ROLE_GROUP_LIST_SUCCESS: "Lấy danh sách nhóm quyền thành công",
        NOT_FOUND_ROLE_GROUP: "Không tìm thấy nhóm quyền!!!",
    },

    dialAutomatically: {
        DELETE_CONTACT_GROUP_SUCCESS: "Xóa nhóm danh bạ thành công",
        GET_CONTACT_GROUP_LIST_SUCCESS: "Lấy danh sách nhóm danh bạ thành công",
        GET_CONTACT_GROUP_SUCCESS: "Lấy nhóm danh bạ thành công",
        CREATE_GROUP_CONTACT_SUCCESS: "Tạo nhóm danh bạ thành công",
        UPDATE_GROUP_CONTACT_SUCCESS: "Cập nhật nhóm danh bạ thành công",
        NOT_FOUND_CONTACT_GROUP: "Nhóm danh bạ không tồn tại",
        CREATE_DIALER_SUCCESS: "Tạo chiến dịch thành công",
        UPDATE_DIALER_SUCCESS: "Cập nhật chiến dịch thành công",
        DELETE_DIALER_SUCCESS: "Xóa chiến dịch thành công",
        CHANGE_STATUS_SUCCESS: "Cập nhật trạng thái chiến dịch thành công",
        NOT_FOUND_DIALER: "Chiến dịch không tồn tại",
    },
};
module.exports = StatusResponse;
